# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "archlinux/archlinux"

  config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "~/.ssh/id_rsa"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/id_rsa.pub"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.provision "shell", :privileged => false, inline: <<-SHELL
    sudo pacman -Sy --noconfirm git
    clone git@github.com:steven-joruk/dotfiles.git .dotfiles
    cd .dotfiles
    ./install.sh
  SHELL
end
